In [1]:
import pandas as pd
df = pd.read_csv("../data/mobile_new.csv")

### Ridge Regression

In ridge regression we assign the L2 panalty. It has the following form

$RSS+\lambda\sum\beta_{i}^2$

$\lambda$ controls the severity of the penaty, if $\lambda$ is a big number then coefficent estimates will be shrunk aggressively

In [2]:
df.head(2)

screen_size  rear_camera_mp  front_camera_mp  ram  battery  weight  \
0         14.5            13.0              5.0  3.0   3020.0   146.0   
1         17.3            13.0             16.0  8.0   4300.0   213.0   

   normalized_used_price  
0               4.307572  
1               5.162097

In [3]:
X = df[['screen_size','rear_camera_mp','front_camera_mp','ram']].values
y = df['normalized_used_price'].values

In [4]:
from sklearn.linear_model import Ridge

In [5]:
m = Ridge(alpha=2) ### alpha<->lambda
m = m.fit(X,y)

In [6]:
m.intercept_

2.5411183543988445

In [7]:
m.coef_

array([0.06748184, 0.04462648, 0.02173224, 0.08243674])

In [14]:
### Increase the alpha to a large value
m = Ridge(alpha=10000000) ### alpha<->lambda
m = m.fit(X,y)

In [15]:
m.intercept_

4.324640365540873

In [16]:
m.coef_ ## coefficient values have descreased

array([0.00044214, 0.00052555, 0.00072357, 0.00011395])

### How to choose $\lambda$ or $\alpha$?

Use kfold cross validation. For each value of lambda or alpha, find out what is the average value of a performance metric: $adj r^2$ or MSE

In [17]:
from sklearn.model_selection import GridSearchCV

In [33]:
import numpy as np
lambda_grid = np.arange(1,100,2)

In [34]:
m = GridSearchCV(Ridge(),param_grid = {'alpha':lambda_grid},cv=3)

In [ ]:
m=m.fit(X,y)

In [37]:
m.best_params_

{'alpha': 1}

### We can change the pefromance metric by defining our own scoring function

In [42]:
m =  GridSearchCV(Ridge(),param_grid={'alpha':lambda_grid},cv=3,scoring='neg_mean_squared_error') ### ref: https://scikit-learn.org/stable/modules/model_evaluation.html#scoring
m = m.fit(X,y)                

In [43]:
m.best_params_

{'alpha': 1}

## Lasso Regression

In lasso regression we use the L1 norm and minimize the following cost function:

$RSS+\lambda\sum|\beta_i|$

In [44]:
from sklearn.linear_model import Lasso

In [49]:
m = Lasso(alpha = 1) ## alpha<-> lambda

In [50]:
m = m.fit(X,y)

In [51]:
m.intercept_

3.9099283227258845

In [52]:
m.coef_ ## l1 penalty is severe, you can see some of the coeff have been made zero

array([0.01261408, 0.01236221, 0.02330867, 0.        ])

### How to choose $\lambda$ or $\alpha$?

Use kfold cross validation. For each value of lambda or alpha, find out what is the average value of a performance metric: $adj r^2$ or MSE

In [55]:
alpha_grid = np.arange(0.1,4,0.1)

In [56]:
m =  GridSearchCV(Lasso(),param_grid={'alpha':alpha_grid},cv=3,scoring='neg_mean_squared_error') ### ref: https://scikit-learn.org/stable/modules/model_evaluation.html#scoring
m = m.fit(X,y) 

In [57]:
m.best_params_

{'alpha': 0.1}